
INSERT INTO library (id, name) VALUES (1, 'Miguel Hidalgo');
INSERT INTO library (id, name) VALUES (2, 'Leonidovo');
INSERT INTO library (id, name) VALUES (3, 'Chonghe');
INSERT INTO library (id, name) VALUES (4, 'Berezayka');
INSERT INTO library (id, name) VALUES (5, 'Kolç');
INSERT INTO library (id, name) VALUES (6, 'Kadusimbar');
INSERT INTO library (id, name) VALUES (7, 'Biny Selo');
INSERT INTO library (id, name) VALUES (8, 'Cabittaogan');
INSERT INTO library (id, name) VALUES (9, 'Nine');
INSERT INTO library (id, name) VALUES (10, 'Puyang');
INSERT INTO library (id, name) VALUES (11, 'Pantang');
INSERT INTO library (id, name) VALUES (12, 'Little Rock');
INSERT INTO library (id, name) VALUES (13, 'Zangzhai');
INSERT INTO library (id, name) VALUES (14, 'Pamplona/Iruña');
INSERT INTO library (id, name) VALUES (15, 'Lille');
INSERT INTO library (id, name) VALUES (16, 'Xinchengzi');
INSERT INTO library (id, name) VALUES (17, 'Ash Shuyūkh');
INSERT INTO library (id, name) VALUES (18, 'Vlachovice');
INSERT INTO library (id, name) VALUES (19, 'Židlochovice');
INSERT INTO library (id, name) VALUES (20, 'Lacombe');
INSERT INTO library (id, name) VALUES (21, 'Krajan Tengah');
INSERT INTO library (id, name) VALUES (22, 'Ōno-hara');
INSERT INTO library (id, name) VALUES (23, 'Santana');
INSERT INTO library (id, name) VALUES (24, 'Sumusţā as Sulţānī');
INSERT INTO library (id, name) VALUES (25, 'Mauhao');
INSERT INTO library (id, name) VALUES (26, 'San Rafael');
INSERT INTO library (id, name) VALUES (27, 'Vera Cruz');
INSERT INTO library (id, name) VALUES (28, 'Manalad');
INSERT INTO library (id, name) VALUES (29, 'Kembang');
INSERT INTO library (id, name) VALUES (30, 'Baltimore');
INSERT INTO library (id, name) VALUES (31, 'Lagoa Santa');
INSERT INTO library (id, name) VALUES (32, 'Kayakent');
INSERT INTO library (id, name) VALUES (33, 'Umeå');
INSERT INTO library (id, name) VALUES (34, 'São Paio de Seide');
INSERT INTO library (id, name) VALUES (35, 'Chociwel');
INSERT INTO library (id, name) VALUES (36, 'Herzliya Pituah');
INSERT INTO library (id, name) VALUES (37, 'Kalianget');
INSERT INTO library (id, name) VALUES (38, 'Cincinnati');
INSERT INTO library (id, name) VALUES (39, 'Maroa');
INSERT INTO library (id, name) VALUES (40, 'Zhonghechang');
INSERT INTO library (id, name) VALUES (41, 'Douane');
INSERT INTO library (id, name) VALUES (42, 'Gaotai');
INSERT INTO library (id, name) VALUES (43, 'Takari');
INSERT INTO library (id, name) VALUES (44, 'Kafr Sawm');
INSERT INTO library (id, name) VALUES (45, 'Golug');
INSERT INTO library (id, name) VALUES (46, 'Tunggar');
INSERT INTO library (id, name) VALUES (47, 'Caomiao');
INSERT INTO library (id, name) VALUES (48, 'Lecherías');
INSERT INTO library (id, name) VALUES (49, 'Parintins');
INSERT INTO library (id, name) VALUES (50, 'Baofeng');
INSERT INTO library (id, name) VALUES (51, 'Malaryta');
INSERT INTO library (id, name) VALUES (52, 'Linshui');
INSERT INTO library (id, name) VALUES (53, 'Coripata');
INSERT INTO library (id, name) VALUES (54, 'Novokuybyshevsk');
INSERT INTO library (id, name) VALUES (55, 'Karkkila');
INSERT INTO library (id, name) VALUES (56, 'Jingang');
INSERT INTO library (id, name) VALUES (57, 'Lesnoye');
INSERT INTO library (id, name) VALUES (58, 'Ayotupas');
INSERT INTO library (id, name) VALUES (59, 'Francisco Villa');
INSERT INTO library (id, name) VALUES (60, 'Orekhovo-Zuyevo');
INSERT INTO library (id, name) VALUES (61, 'Yanaoca');
INSERT INTO library (id, name) VALUES (62, 'Dijon');
INSERT INTO library (id, name) VALUES (63, 'Piteå');
INSERT INTO library (id, name) VALUES (64, 'Komorniki');
INSERT INTO library (id, name) VALUES (65, 'Ban Tak');
INSERT INTO library (id, name) VALUES (66, 'Rāwandūz');
INSERT INTO library (id, name) VALUES (67, 'Yatsuomachi-higashikumisaka');
INSERT INTO library (id, name) VALUES (68, 'Buseresere');
INSERT INTO library (id, name) VALUES (69, 'Wonokerto');
INSERT INTO library (id, name) VALUES (70, 'Qal‘eh-ye Khvājeh');
INSERT INTO library (id, name) VALUES (71, 'Três Passos');
INSERT INTO library (id, name) VALUES (72, 'Itatuba');
INSERT INTO library (id, name) VALUES (73, 'Goyang-si');
INSERT INTO library (id, name) VALUES (74, 'Nizhyn');
INSERT INTO library (id, name) VALUES (75, 'Haiyanmiao');
INSERT INTO library (id, name) VALUES (76, 'Lipin Bor');
INSERT INTO library (id, name) VALUES (77, 'Borbon');
INSERT INTO library (id, name) VALUES (78, 'Pervomayskoye');
INSERT INTO library (id, name) VALUES (79, 'Kuilehe');
INSERT INTO library (id, name) VALUES (80, 'Raemude');
INSERT INTO library (id, name) VALUES (81, 'Kanugrahan');
INSERT INTO library (id, name) VALUES (82, 'Unity');
INSERT INTO library (id, name) VALUES (83, 'Zarrīn Shahr');
INSERT INTO library (id, name) VALUES (84, 'Constantia');
INSERT INTO library (id, name) VALUES (85, 'Biggar');
INSERT INTO library (id, name) VALUES (86, 'Cobre');
INSERT INTO library (id, name) VALUES (87, 'Bamusso');
INSERT INTO library (id, name) VALUES (88, 'Vista Hermosa');
INSERT INTO library (id, name) VALUES (89, 'Dangbigih');
INSERT INTO library (id, name) VALUES (90, 'Wu’erbu Baolige');
INSERT INTO library (id, name) VALUES (91, 'Sañgay');
INSERT INTO library (id, name) VALUES (92, 'Mazra‘at Bayt Jinn');
INSERT INTO library (id, name) VALUES (93, 'Jiepai');
INSERT INTO library (id, name) VALUES (94, 'Zhantang');
INSERT INTO library (id, name) VALUES (95, 'Quillabamba');
INSERT INTO library (id, name) VALUES (96, 'Muraharjo');
INSERT INTO library (id, name) VALUES (97, 'Ziyang');
INSERT INTO library (id, name) VALUES (98, 'Sangiang');
INSERT INTO library (id, name) VALUES (99, 'Liuhe');
INSERT INTO library (id, name) VALUES (100, 'Mascote');
INSERT INTO library (id, name) VALUES (101, 'Huwan');
